version: "3.8"

services:
  pionflo-bot:
    container_name: pionflo-bot
    restart: always
    build:
      context: ./app
    working_dir: /usr/pionflo-bot/app
    command: python -m main
    env_file: ./app/.env
    networks:
      - pionflo-network
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      pionflo-bot-db:
        condition: service_healthy
  
  pionflo-bot-db:
    image: postgres:16-alpine
    container_name: pionflo-bot-db
    restart: always
    command: -p ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pionflo-network
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pionflo-bot-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 60s
      timeout: 3s
      retries: 3

volumes:
  pionflo-bot-db-data:

networks:
  pionflo-network:
    name: dtp-network-${ENVIRONMENT}
    external: false
